### ISSUE TITLE
Quantile regression error

### ISSUE THREAD

**Issue by Farkal** [adumasphi/otpod#1]
When i run this code with [test_Signal.xlsx](https://github.com/adumasphi/otpod/files/995636/test_Signal.xlsx):
```
np_data = pandas.read_excel(my_excel_file).values
final_array = self.np_data[:, :2].T
for i in range(2, self.np_data.shape[1]):
    final_array = np.hstack((final_array, np.vstack((self.np_data[:, 0], self.np_data[:, i]))))
otpod.QuantileRegressionPOD(final_array[0], final_array[1],
                                                         400.0,
                                                         150.0,
                                                         3000.0,
                                                         boxCox=False)
```
I got:
`RuntimeError: InternalException : Error: Brent method requires that the function takes different signs at the endpoints of the given starting interval, here infPoint=0, supPoint=1.65, value=400, f(infPoint) - value=5.73543 and f(supPoint) - value=2871.86`

**Comment by adumasphi** [comment]
This error appeared when the confidence interval is built using bootstrap. For small probabilities, there was no positive defect values so the Brent algorithm returns an error. As it is used only to compute the distribution of the defect for a given target probability, I authorized to compute negative defects otherwise it will bias the asymptotic distribution.
I also improved the exceptions management.
